package com.keyxentic.samlsptestharness.credential;

import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;
import org.bouncycastle.cert.X509CertificateHolder;
import org.bouncycastle.cert.X509v3CertificateBuilder;
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter;
import org.bouncycastle.operator.ContentSigner;
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder;

import java.io.IOException;
import java.io.OutputStream;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.SecureRandom;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.time.Duration;
import java.time.Instant;
import java.util.Date;

/**
 * Loads the SP's signing credential from a PKCS12 keystore file if one is already
 * present at the given path (whether generated by a previous boot or supplied by
 * the operator), otherwise generates a new RSA keypair + self-signed certificate
 * and persists it there.
 */
public class SpCredentialService {

    private static final String ALIAS = "sp";
    private static final char[] PASSWORD = "sp-credential".toCharArray();
    private static final String SUBJECT = "CN=saml-sp-test-harness";
    private static final Duration VALIDITY = Duration.ofDays(365 * 5);

    public SpCredential loadOrGenerate(Path keystorePath) {
        try {
            if (Files.exists(keystorePath)) {
                return load(keystorePath);
            }
            SpCredential generated = generate();
            save(generated, keystorePath);
            return generated;
        } catch (GeneralSecurityException | IOException e) {
            throw new SpCredentialException("Could not load or generate the SP credential at " + keystorePath, e);
        }
    }

    private SpCredential load(Path keystorePath) throws GeneralSecurityException, IOException {
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        try (var in = Files.newInputStream(keystorePath)) {
            keyStore.load(in, PASSWORD);
        }
        PrivateKey privateKey = (PrivateKey) keyStore.getKey(ALIAS, PASSWORD);
        X509Certificate certificate = (X509Certificate) keyStore.getCertificate(ALIAS);
        return new SpCredential(new KeyPair(certificate.getPublicKey(), privateKey), certificate);
    }

    private void save(SpCredential credential, Path keystorePath) throws GeneralSecurityException, IOException {
        Files.createDirectories(keystorePath.getParent());
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        keyStore.load(null, null);
        Certificate[] chain = {credential.certificate()};
        keyStore.setKeyEntry(ALIAS, credential.keyPair().getPrivate(), PASSWORD, chain);
        try (OutputStream out = Files.newOutputStream(keystorePath)) {
            keyStore.store(out, PASSWORD);
        }
    }

    private SpCredential generate() throws GeneralSecurityException {
        KeyPair keyPair = generateRsaKeyPair();
        X509Certificate certificate = selfSign(keyPair);
        return new SpCredential(keyPair, certificate);
    }

    private KeyPair generateRsaKeyPair() throws NoSuchAlgorithmException {
        KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
        generator.initialize(2048, new SecureRandom());
        return generator.generateKeyPair();
    }

    private X509Certificate selfSign(KeyPair keyPair) throws GeneralSecurityException {
        try {
            X500Name subject = new X500Name(SUBJECT);
            Instant notBefore = Instant.now();
            Instant notAfter = notBefore.plus(VALIDITY);
            BigInteger serial = new BigInteger(128, new SecureRandom());

            SubjectPublicKeyInfo publicKeyInfo = SubjectPublicKeyInfo.getInstance(keyPair.getPublic().getEncoded());
            X509v3CertificateBuilder builder = new X509v3CertificateBuilder(
                    subject, serial, Date.from(notBefore), Date.from(notAfter), subject, publicKeyInfo);

            ContentSigner signer = new JcaContentSignerBuilder("SHA256withRSA").build(keyPair.getPrivate());
            X509CertificateHolder holder = builder.build(signer);
            return new JcaX509CertificateConverter().getCertificate(holder);
        } catch (org.bouncycastle.operator.OperatorCreationException | java.security.cert.CertificateException e) {
            throw new CertificateGenerationException(e);
        }
    }

    private static final class CertificateGenerationException extends GeneralSecurityException {
        CertificateGenerationException(Exception cause) {
            super(cause);
        }
    }
}
